AgroFresh/urls.py
#!/usr/bin/python3

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('inbox/', include('chat.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
#!/usr/bin/python3

from django.urls import path

from . import views

app_name = 'chat'

urlpatterns = [
        path('', views.inbox, name='inbox'),
        path('<int:pk>/', views.detail, name='detail'),
        path('new/<int:item_pk>/', views.new_chat, name='new'),
        ]

conversation/urls.py
#!/usr/bin/python3

from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
        path('', views.inbox, name='inbox'),
        path('<int:pk>/', views.detail, name='detail'),
        path('new/<int:item_pk>/', views.new_conversation, name='new'),
        ]

conversation/models.py
#!/usr/bin/python3

from django.db import models
from django.contrib.auth.models import User

from item.models import Item

class Conversation(models.Model):
    item = models.ForeignKey(Item, related_name='conversations', on_delete=models.CASCADE)
    members = models.ManyToManyField(User, related_name='conversations')
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-modified_at',)


class ConversationMessage(models.Model):
    conversation = models.ForeignKey(Conversation, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='created_messages', on_delete=models.CASCADE)

conversation/forms.py
#!/usr/bin/python3

from django import forms
from .models import ConversationMessage

class ConversationMessageForm(forms.ModelForm):
    class Meta:
        model = ConversationMessage
        fields = ('content',)
        widgets = {
                'content': forms.Textarea(attrs={
                    'class': 'w-full py-4 px-6 rounded-xl border'
                    })
                }

conversation/templates/conversation/detail.html
{% extends 'core/base.html' %}

{% block title %}Conversation{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">Conversation</h1>

<div class="space-y-6">
	{% for message in conversation.messages.all %}
	<div class="p-6 flex {% if message.created_by == request.user %}bg-blue-100{% else %}bg-gray-100{% endif %}">
		<div>
			<p class="mb-4"><strong>{{ message.created_by.username }}</strong> @ {{ message.created_at }}</p>
			<p>{{ message.content }}</p>
		</div>
	</div>
	{% endfor %}
</div>

<form method="post" action="." class="mt-6">
	{% csrf_token %}

	{{ form.as_p }}

	<button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Send</button>
</form>

{% endblock %}

conversation/templates/conversation/inbox.html
{% extends 'core/base.html' %}

{% block title %}Inbox{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">Inbox</h1>

<div class="space-y-6">
	{% for conversation in conversations %}
	<a href="{% url 'conversation:detail' conversation.id %}">
		<div class="p-6 flex bg-gray-100 rounded-xl">
			<div class="pr-6">
				<img src="{{ conversation.item.image.url }}" class="w-20 rounded-xl">
			</div>

			<div>
				{% for member in conversation.members.all %}
				{% if member != request.user %}
				<p class="mb-4"><strong>{{ member.username}}</strong> | {{ conversation.modified_at }}</p>
				<p>{{ conversation.item.name }}</p>
				{% endif %}
				{% endfor %}
			</div>
		</div>
	</a>
	{% endfor %}
</div>

{% endblock %}

conversation/templates/conversation/new.html
{% extends 'core/base.html' %}

{% block title %}New conversation{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">New conversation</h1>

<form method="post" action=".">
        {% csrf_token %}

        <div class="space-y-4">
                {{ form.as_p }}
        </div>

        {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                        {% for field in form %}
                        {{ field.errors }}
                        {% endfor %}

                        {{ form.non_field_errors }}
                </div>
        {% endif %}

        <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Send</button>
</form>

{% endblock %}